name: Python CI

on:
  push:
    branches:
      - main
  pull_request:          # <-- 'pull_request', not 'push_request'
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest   # <-- should be 'runs-on', not 'run-on'

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2   # <-- 'actions', not 'action'
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt   # <-- file name spelling corrected

      - name: Run tests
        run: pytest
